### ISSUE TITLE
table1 documentation example with dplyr pipe not working?

### ISSUE THREAD

**Issue by apatel9437** [TysonStanley/furniture#13]
Hi,

I was trying to use table1 from the furniture package, and tried to replicate the following example from the documentation: 

df %>%
  table1(x, y, z, 
         splitby = ~a) %>%
  summarise(count = n())

but it produced the following error: 

Error in UseMethod("summarise_") : 
  no applicable method for 'summarise_' applied to an object of class "table1"

Please let me know if this a typo in the documentation, and whether you are able to pass dplyr summary functions to table1. I've been messing around with it but it doesn't seem possible.

Thanks!

**Comment by TysonStanley** [comment]
Hi,

 

That is definitely a typo since the last major release. Table1() used to provide the original data set after providing the table but that caused more problems overall so we changed that to just return the table itself. I’ll update that in the GitHub documentation right now and hopefully get that submitted to CRAN over the next week since there’s a release coming up.

 

Thanks!

Tyson
